"""initial schema

Revision ID: b6a8d05e8b5a
Revises: 
Create Date: 2026-04-25 21:44:03.123171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# This avoids a NameError: name 'data' is not defined
# for custom types
import data.orm.types


# revision identifiers, used by Alembic.
revision: str = 'b6a8d05e8b5a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decks',
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('colors', data.orm.types.ColorSetType(), nullable=True),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cards',
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('deck_id', sa.Uuid(), nullable=True),
    sa.Column('scryfall_id', sa.Uuid(), nullable=True),
    sa.Column('gatherer_id', sa.String(), nullable=True),
    sa.Column('tcgplayer_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mana_cost', sa.String(), nullable=True),
    sa.Column('cmc', sa.Numeric(), nullable=True),
    sa.Column('color', data.orm.types.ColorSetType(), nullable=True),
    sa.Column('color_identity', data.orm.types.ColorSetType(), nullable=True),
    sa.Column('type_line', sa.String(), nullable=True),
    sa.Column('oracle_text', sa.Text(), nullable=True),
    sa.Column('power', sa.String(), nullable=True),
    sa.Column('toughness', sa.String(), nullable=True),
    sa.Column('rarity', sa.String(), nullable=True),
    sa.Column('set_name', sa.String(), nullable=True),
    sa.Column('set_code', sa.String(), nullable=True),
    sa.Column('set_id', sa.Uuid(), nullable=True),
    sa.Column('collector_number', sa.String(), nullable=True),
    sa.Column('flavor_text', sa.Text(), nullable=True),
    sa.Column('condition', data.orm.types.ConditionType(), nullable=False),
    sa.Column('foil', sa.Boolean(), nullable=False),
    sa.Column('prints_search_uri', sa.String(), nullable=True),
    sa.Column('scryfall_uri', sa.String(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('artists', sa.Text(), nullable=True),
    sa.Column('is_reserved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    op.drop_table('decks')
    op.drop_table('locations')
    # ### end Alembic commands ###
